#!/bin/bash
#PBS -N job1
#PBS -l nodes=1:ppn=1
#PBS -l mem=30gb
#PBS -q long
#PBS -j oe
#PBS -o /data1/aafgarci/jhonathan/resul_syng-proj/outs/job-r_script_syng-proj_mini-batch_model3.out


PREFIX_python=/home/aafgarci/anaconda3/bin
PREFIX_code=/data1/aafgarci/jhonathan/sorghum-multi-trait/codes

n_proc=2
n_alt=2

for i in $(seq 0 $((n_proc-1))); do  
	
	${PREFIX_python}/python ${PREFIX_code}/mtrait_cross_validation_and_models.py -c ${i} -nalt ${n_alt} &

	sleep 1

done;


